# Generated by Django 3.1 on 2020-10-12 11:18

from django.db import migrations, models
import django.db.models.deletion
import shop_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, verbose_name='first name')),
                ('last_name', models.CharField(max_length=254, verbose_name='last name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'processing'), (2, 'done'), (3, 'canceled')], default=0, verbose_name='status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(upload_to=shop_app.models.image_upload_path, verbose_name='image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop_app.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
