# Generated by Django 3.1 on 2020-10-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='shop_app.OrderItems', to='shop_app.Product'),
        ),
    ]
